Vagrant.configure("2") do |config|
    config.hostmanager.enable = true
    config.hostmanager.manage_host = true

### DB VM ###
    config.vm.define "db01" do |db01|
        db01.vm.box = "eurolinux-vagrant/centos-stream-9"
        db01.vm.box_version = "9.0.43"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.15"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "512"  
        end
    end

### Memcache vm ###
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
        mc01.vm.box_version = "9.0.43"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.56.14"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "512" 
        end
    end

### RabbitMQ vm ###
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
        rmq01.vm.box_version = "9.0.43"
        rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", ip: "192.168.56.13"
        rmq01.vm.provider "virtualbox" do |vb|
            vb.memory = "512"  
        end
    end

### Nginx VM ###
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.12"
        web01.vm.provider "virtualbox" do |vb|
            #vb.gui = true # este campo esta me dando o erro: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
            vb.memory = "750"  
            vb.check_guest_additions = false
        end
    end
end